name: mcpnet
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.7  # Optional if using GPU
  - easydict
  - tensorboard
  - pip
  - pip:
    - transformers
    - tokenizers

